#!/usr/bin/with-contenv bash

# add render group
groupadd render

# check for the existence of a video and/or tuner device
if [ -e /dev/dri ] || [ -e /dev/dvb ]; then
	if [ -e /dev/dri ]; then
		VIDEO_GID=$(stat -c '%g' /dev/dri/* | grep -v '^0$' | head -n 1)
		RENDER_GID=$(stat -c '%g' /dev/dri/* | grep -v '^0$' | head -n 2 | tail -1)
	else
		if [ ! "${VIDEO_GID}" == '0' ]; then
			VIDEO_NAME=$(getent group "${VIDEO_GID}" | awk -F: '{print $1}')
			if [ -z "${VIDEO_NAME}" ]; then
				VIDEO_NAME="video$(head /dev/urandom | tr -dc 'a-z0-9' | head -c8)"
				groupadd "$VIDEO_NAME"
				groupmod -g "$VIDEO_GID" "$VIDEO_NAME"
			fi
			usermod -a -G "$VIDEO_NAME" abc
			touch /groupadd
		fi
	fi
done

if [ -n "${FILES}" ] && [ ! -f "/groupadd" ]; then
	usermod -a -G root abc
fi

# Check if the GID is taken and swap to 65533
CURRENT=$(getent group ${VIDEO_GID} | awk -F: '{print $1}')
if [ -z "${CURRENT}" ] || [ "${CURRENT}" == 'video' ]; then
	groupmod -g ${VIDEO_GID} video
	groupmod -g ${RENDER_GID} render
	usermod -a -G video abc
	usermod -a -G render abc
else
	groupmod -g 65533 ${CURRENT}
	groupmod -g ${VIDEO_GID} video
	groupmod -g ${RENDER_GID} render
	usermod -a -G video abc
	usermod -a -G render abc
fi
